services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5174:5173"
    networks:
      - forminit
    env_file:
      - ./client/.env
    volumes:
      - .:/app
      - client_node_modules:/app/node_modules


  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3100:3000"
    networks:
      - forminit
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules

  mongo:
    image: mongodb/mongodb-community-server:7.0.3-ubi8-20241108T082135Z
    container_name: mongo
    networks:
      - forminit
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

networks:
  forminit:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  client_node_modules: {}
  backend_node_modules: {}
