name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "manifests/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install-civo
        uses: civo/action-civo@v1.0.0
        with:
          token: ${{secrets.CIVO_TOKEN}}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Make config folder
        run: mkdir ~/.kube

      - name: Set region
        run: civo region current ${{secrets.CIVO_REGION}}

      - name: Save cluster config details to kubeconfig
        run: civo kubernetes config ${{secrets.CIVO_CLUSTER_NAME}} --save --local-path ~/.kube/config -y

      - name: Apply Kubernetes manifests
        run: kubectl apply -f manifests/k8s
