name: tests-client

on:
  pull_request:
    paths:
      - "client/**"
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && npm install && npm run test
