name: tests-auth

on:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd backend && npm install && npm run test
